



main:
	c++ -Wno-deprecated pcl_transformation.cpp -o pcl_transformation -I/usr/include/pcl-1.7 -I/usr/include/eigen3 -I/usr/include/ -I/usr/include/vtk-5.8/ -lpcl_io -lflann_cpp -lflann_cpp-gd -lboost_system -lpcl_common -lvtkCommon -lvtkFiltering -lpcl_visualization -lvtkRendering
