
main:
	g++ -I. -I /home/mbianchi/tesis/lepetit-codigo/DOT_vs_1.0/resources/ESM/inc/ -I $IPPROOT/include `pkg-config opencv --cflags` -L $IPPROOT/lib/intel4 main_wil.cc -o main_will `pkg-config opencv --libs`
